=== windowsair/cabotisocks/config/config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "version",
    "server",
    "cgroup",
    "rules"
  ],
  "properties": {
    "version": {
      "type": "string",
      "enum": [
        "1"
      ]
    },
    "server": {
      "type": "object",
      "required": [
        "type",
        "host",
        "port"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "socks5"
          ]
        },
        "host": {
          "type": "string",
          "minLength": 1
        },
        "port": {
          "type": "integer",
          "minimum": 0,
          "maximum": 65535
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "misc": {
      "type": "object",
      "properties": {
        "enable_udp": {
          "type": "boolean"
        }
      }
    },
    "cgroup": {
      "type": "object",
      "required": [
        "include_path"
      ],
      "properties": {
        "include_path": {
          "type": "string",
          "minLength": 1
        },
        "exclude_path": {
          "type": "string"
        }
      }
    },
    "rules": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "type": "object",
        "required": [
          "action"
        ],
        "properties": {
          "port": {
            "type": "integer",
            "minimum": 0,
            "maximum": 65535
          },
          "process": {
            "type": "string"
          },
          "host": {
            "type": "array",
            "minItems": 1,
            "maxItems": 4096,
            "items": {
              "type": "string"
            }
          },
          "action": {
            "type": "string",
            "enum": [
              "direct",
              "proxy",
              "block"
            ]
          }
        }
      }
    }
  }
}

=== windowsair/cabotisocks/config/config.example.json
{
  "version": "1",
  "server": {
    "type": "socks5",
    "host": "127.0.0.1",
    "port": 10808,
    "username": "",
    "password": ""
  },
  "misc": {
    "enable_udp": true
  },
  "cgroup": {
    "include_path": "/cabotisocks",
    "exclude_path": "/system.slice/"
  },
  "rules": [
    {
      "name": "Bypass local",
      "host": [
        "0.0.0.0/8",
        "10.0.0.0/8",
        "100.64.0.0/10",
        "127.0.0.0/8",
        "169.254.0.0/16",
        "172.16.0.0/12",
        "192.0.0.0/24",
        "192.0.2.0/24",
        "192.88.99.0/24",
        "192.168.0.0/16",
        "198.18.0.0/15",
        "198.51.100.0/24",
        "203.0.113.0/24",
        "224.0.0.0/3"
      ],
      "action": "direct"
    },
    {
      "name": "proxy",
      "action": "proxy"
    }
  ]
}
